# Generated by Django 4.0.3 on 2022-04-04 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_massage_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['updated', 'created']},
        ),
        migrations.RenameField(
            model_name='massage',
            old_name='updatet',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='updatet',
            new_name='updated',
        ),
    ]
